// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/accounts": {
    params: {};
  };
  "/budget-detail": {
    params: {};
  };
  "/categories": {
    params: {};
  };
  "/financial-assets": {
    params: {};
  };
  "/reports": {
    params: {};
  };
  "/ai-assistant": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/accounts" | "/budget-detail" | "/categories" | "/financial-assets" | "/reports" | "/ai-assistant" | "/settings" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/accounts.tsx": {
    id: "routes/accounts";
    page: "/accounts";
  };
  "routes/budget-detail.tsx": {
    id: "routes/budget-detail";
    page: "/budget-detail";
  };
  "routes/categories.tsx": {
    id: "routes/categories";
    page: "/categories";
  };
  "routes/financial-assets.tsx": {
    id: "routes/financial-assets";
    page: "/financial-assets";
  };
  "routes/reports.tsx": {
    id: "routes/reports";
    page: "/reports";
  };
  "routes/ai-assistant.tsx": {
    id: "routes/ai-assistant";
    page: "/ai-assistant";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/accounts": typeof import("./app/routes/accounts.tsx");
  "routes/budget-detail": typeof import("./app/routes/budget-detail.tsx");
  "routes/categories": typeof import("./app/routes/categories.tsx");
  "routes/financial-assets": typeof import("./app/routes/financial-assets.tsx");
  "routes/reports": typeof import("./app/routes/reports.tsx");
  "routes/ai-assistant": typeof import("./app/routes/ai-assistant.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};